# Author: Vincenzo Merola <vincenzo.merola2@unina.it>
# Description:
#		This Makefile builds NVDLA VP:
#		1. Compile loadable from nets:
#			- AlexNet
#			- ResNet
#		2. Configure Docker container
#		3. Check for built sw

all: container net sw

.PHONY: container net sw